### ISSUE TITLE
The detailed commands for building TFLite GPU delegate so files 

### ISSUE THREAD

**Issue by rose-jinyang** [zldrobit/onnx_tflite_yolov3#14]
## 🚀 Feature

I want to get the correct steps & command for building OpenCL backend TFLite GPU delegate so file for aarch64 platform on host PC or aarch64 platform.

## Motivation
I am going to use OpenCL backend TFLite runtime on RK3399 Ubuntu 18.04 LTS aarch64.
So I tried to build OpenCL backend TFLite GPU delegate so file by using Bazel.
I found that u built OpenCL backend GPU delegate and OpenGL backend GPU delegate for x86_64.
Could u provide the correct steps & commands to build OpenCL backend tflite GPU delegate so file and OpenGL backend tflite GPU delegate so file?
Thanks

**Comment by WillLiGitHub** [comment]
I have same question,  can you show the detailed commands for building  libtensorflowlite_gpu_gl.so.
thanks !!!

**Comment by zldrobit** [comment]
@WillLiGitHub You could refer to the command I used to build GPU delegate:
https://github.com/tensorflow/tensorflow/issues/38336#issuecomment-642384587,
and the issue about building it:
https://github.com/zldrobit/onnx_tflite_yolov3/issues/15

**Comment by WillLiGitHub** [comment]
@zldrobit thanks for you help!
i have solved this problem.
