### ISSUE TITLE
Segmentation fault(core dump)

### ISSUE THREAD

**Issue by Kevin-Wei-Chih** [zldrobit/onnx_tflite_yolov3#23]
## 🐛 Bug
I ran the docker image that author provided.
Then, I ran python3 detect.py --cfg cfg/yolov3.cfg --weights weights/yolov3.weights
I got the error shown below.
------------error message-----------------
Segmentation fault (core dumped)
![image](https://user-images.githubusercontent.com/57010307/132940029-f6a4c931-d870-420f-9772-8a148e7c1d4b.png)

------------------------------------------------------------
I am not sure whether the docker image has something error or not.
Do anyone know what is the exact problem?
Thanks!

**Comment by zldrobit** [comment]
@Kevin-Wei-Chih I encounter this problem as well in converting the PyTorch model to an ONNX model. The segfault message does not affect the ONNX conversion. You could try to run `detect.py` with the exported ONNX model and get a correct result.

**Comment by Kevin-Wei-Chih** [comment]
I have already solved the issue.
Change the onnx version to 1.5.0 instead of 1.6.0. 
It worked for me.
Because there have some issue in the onnx==1.6.0

Anyway,thanks for your response!
This code helps me a lot!
